py_binary(
    name = "make_parser_spec",
    srcs = ["make_parser_spec.py"],
    deps = [
        "//dragnn/protos:spec_py_pb2",
        "//dragnn/python:spec_builder",
        "//syntaxnet:dictionary_py_pb2",
        "@org_tensorflow//tensorflow:tensorflow_py",
    ],
)
